# Generated by Django 4.2.1 on 2023-07-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover_book_ebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
